import { Doctor } from './types';

// Using consistent avatar style
const AVATAR_BASE = "https://api.dicebear.com/7.x/avataaars/svg?seed=";

export const DOCTORS: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Arman Hosen Patoary',
    specialty: 'GENERAL PHYSICIAN',
    category: 'Physician',
    degrees: 'MBBS, FCPS (Medicine)',
    affiliation: 'Dhaka Medical College',
    avatarUrl: `${AVATAR_BASE}Arman`,
    available: true,
  },
  {
    id: '2',
    name: 'Dr. Sohel Rahman',
    specialty: 'MEDICINE',
    category: 'Medicine',
    degrees: 'MBBS, MD (Internal Medicine)',
    affiliation: 'Apollo Hospital',
    avatarUrl: `${AVATAR_BASE}Sohel`,
    available: true,
  },
  {
    id: '3',
    name: 'Dr. Abdullah Al Noman',
    specialty: 'PHYSICIAN',
    category: 'Physician',
    degrees: 'MBBS, M Phil (Radiotherapy)',
    affiliation: 'Rangpur Medical College',
    avatarUrl: `${AVATAR_BASE}Abdullah`,
    available: true,
  },
  {
    id: '4',
    name: 'Dr. Mahbubor Rahman',
    specialty: 'ONCOLOGY',
    category: 'Oncology',
    degrees: 'MBBS, FCPS',
    affiliation: 'Assistant Professor, DMC',
    avatarUrl: `${AVATAR_BASE}Mahbubor`,
    available: true,
  },
  {
    id: '5',
    name: 'Dr. Mahfuzur Rahman',
    specialty: 'MEDICINE',
    category: 'Medicine',
    degrees: 'MBBS, M Phil (Medicine)',
    affiliation: 'Director, MKS',
    avatarUrl: `${AVATAR_BASE}Mahfuzur`,
    available: true,
  },
  {
    id: '6',
    name: 'Dr. Sarah Jenkins',
    specialty: 'CARDIOLOGIST',
    category: 'Cardiologist',
    degrees: 'MD, FACC',
    affiliation: 'City Heart Center',
    avatarUrl: `${AVATAR_BASE}Sarah`,
    available: true,
  },
  {
    id: '7',
    name: 'Dr. Emily Chen',
    specialty: 'ORTHOPEDICS',
    category: 'Orthopedics',
    degrees: 'MBBS, MS (Ortho)',
    affiliation: 'General Hospital',
    avatarUrl: `${AVATAR_BASE}Emily`,
    available: true,
  },
  {
    id: '8',
    name: 'Dr. Robert Stone',
    specialty: 'SURGEON',
    category: 'Surgeon',
    degrees: 'MD, FACS',
    affiliation: 'University Surgery Dept',
    avatarUrl: `${AVATAR_BASE}Robert`,
    available: false,
  },
];